---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
args:
  MASTODON_VERSION: "v4.2.9"
  BASHIO_VERSION: "0.14.3"
  TEMPIO_VERSION: "2021.09.0"
  S6_OVERLAY_VERSION: "3.1.5.0"
